version: "2.1" # optional since v1.27.0
services:
  frontend:
    build: .
    privileged: true
    restart: always
    network_mode: host
    ports:
      - "3000:3000"
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'