name: Build Backend

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
      - run: pnpm install
      - run: pnpm build
        working-directory: packages/cryptoid-backend
